---
title: "Examples of Functions in ThomasZacharyTools"
author: "Zachary Thomas"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


## My functions




```{r}
#func4 example

x1 <- scan(url("http://www.stat.umn.edu/geyer/3701/data/q1p3.txt"))
x2 <- scan(url("http://www.stat.umn.edu/geyer/3701/data/q1p7c.txt"))
x3 <- scan(url("http://www.stat.umn.edu/geyer/3701/data/q1p7b.txt"))
func1 <- function(theta,x) dgamma(x, shape = theta, log = TRUE)
func2 <- function(theta,x) dcauchy(x, location = theta, log = TRUE)
func3 <- function(theta,x) dbinom(x, 20, prob = 1/(1+exp(-theta)), log = TRUE)
func4 <- function(x, func, interval)
{
  f4<-function(theta,x) 
  {sum(func(theta,x))}
  
  oout <- optimize(f4, maximum = TRUE, interval, x=x)
  return(oout$maximum)
}
func4(x1, func1, c(0,3))
func4(x2, func2, c(0,100))
func4(x3, func3, c(-10,10))  

```


```{r}
#func5 example

func5 <- function(x){
  a = sum(x)/length(x)
  b = sum((x-a)^2)/length(x)
  c = sqrt(b)
  return(list(mean=a,var=b,sd=c))
}
func5(rnorm(10))
```

```{r}
#func6 example

func6 <- function(x){
  stopifnot(is.numeric(x))
  stopifnot(length(x)!=0)
  stopifnot(is.finite(x))
  stopifnot(!is.na(x))
  stopifnot(!is.nan(x))
  
  a = sum(x)/length(x)
  b = sum((x-a)^2)/length(x)
  c = sqrt(b)
  return(list(mean=a,var=b,sd=c))
}
func6(rnorm(10))
```


```{r}
#func7 example

func7 <- function(x){
  alpha <- pi
  log <- function(alpha)
    sum(dgamma(x, shape = alpha, log = TRUE))
  interval <- mean(x) + c(-1,1) * 3 * sd(x)
  interval <- pmax(mean(x) / 1e3, interval)
  
  oout<- optimize(log, maximum = TRUE, interval)
  return (oout$maximum)
}
func7(rnorm(10))
```

```{r}
#func8 example

d <- read.table(url("http://www.stat.umn.edu/geyer/3701/data/q1p4.txt"),header = TRUE)

func8 <- function(d){
  
  a = sum(d$x * d$p)
  b = sum(((d$x - a)^2) * d$p)
  c = sqrt(b)
  return(list(mean=a,var=b,sd=c))
  
}
func8(d)
```

```{r}
#func9 example

func9 <- function(x){
  
  tryCatch(stopifnot(is.numeric(x)), error=function(e){print("not numeric")})
  tryCatch(stopifnot(is.finite(x)), error=function(e){print("not finite")})
  tryCatch(stopifnot(length(x)!=0), error=function(e){print("has 0 length")})
  tryCatch(stopifnot(!is.nan(x)), error=function(e){print("NA or NAN")})
  tryCatch(stopifnot(!is.na(x)), error=function(e){print("NA or NAN")})
  
}
func9(NA)
```

```{r}
#func10 example

load(url("http://www.stat.umn.edu/geyer/3701/data/q2p1.rda"))

func10 <- function(A,x)
{
  stopifnot(nrow(A) == ncol(A))
  stopifnot(length(x) == nrow(A))
  stopifnot(is.finite(A))
  stopifnot(is.finite(x))
  X <- cbind(x)
  xt <- t(X)
  Ai <- solve(A)
  m <- xt%*%Ai%*%X
  return(m)
}
func10(a,x)
```

```{r}
#func11 example

load(url("http://www.stat.umn.edu/geyer/3701/data/q2p1.rda"))

"%func11%" <- function(A,x)
{
  stopifnot(nrow(A) == ncol(A))
  stopifnot(length(x) == nrow(A))
  stopifnot(is.finite(A))
  stopifnot(is.finite(x))
  X <- cbind(x)
  xt <- t(X)
  Ai <- solve(A)
  return(xt%*%Ai%*%X)
}
a %func11% x
```

```{r}
#func12 example

load(url("http://www.stat.umn.edu/geyer/3701/data/q2p3.rda"))

func12 <- function(a)
{
  stopifnot(nrow(a) > 1)
  stopifnot(is.finite(a))
  s <- matrix(nr = nrow(a), nc = ncol(a))
  for(i in 1:ncol(a))
  {
    x <- a[,i]
    st <- (x-mean(x))/sd(x)
    s[,i] <- st
  }
  return(s)
}
func12(a)
```

```{r}
#func13 example

load(url("http://www.stat.umn.edu/geyer/3701/data/q2p3.rda"))

func13 <- function(a)
{
  stopifnot(nrow(a) > 1)
  stopifnot(is.finite(a))
  s <- matrix(nrow = nrow(a), ncol = ncol(a))
  m <- apply(a, 2, mean)
  m <- cbind(m)
  m <- t(m)
  st <- apply(a, 2, sd)
  st <- cbind(st)
  st <- t(st)
  s <- apply(a, 1, function(x) ((x-m)/st))
  s <- t(s)
  return(s)
}
func13(a)
```

```{r}
#myapply example

fred <- matrix(1:6, ncol = 2)

myapply <- function(X, MARGIN, FUN, ...)
{
  if(length(dim(X))!=2)
  {
    stop("matrix is not 2d")
  } 
  if(!(MARGIN %in% c(1,2)))
  {
    stop("margin is not in 1 or 2")
  }
  R = dim(X)[1]
  C = dim(X)[2]
  f = match.fun(FUN)
  
  if (MARGIN == 1)
  {
    result = list()
    for(i in 1:R)
    {
      result[[i]] = f(X[i,],...)
    }
  }else if(MARGIN == 2)
  {
    result = list()
    for(j in 1:C)
    {
      result[[j]] = f(X[,j],...)
    }
  }
  return(simplify2array(result))
}
myapply(fred,1,"mean")
myapply(fred, 2, "mean")
myapply(fred, 1, "max")
myapply(fred, 2, "max")
myapply(fred, 1, function(x) quantile(x,0.75))
myapply(fred, 2, function(x) quantile(x,0.75))
myapply(fred,1,"quantile",probs=.75)
myapply(fred,2,"quantile",probs=.75)
myapply(fred,1,"quantile",probs=(1:3)/4)
myapply(fred,2,"quantile",probs=(1:3)/4)
```

```{r}
#dplyr example

farmData <- read.csv("http://users.stat.umn.edu/~almquist/3811_examples/data.csv")
dplyr<- function(x)
  {
  library(magrittr)
  x %>% dplyr::select(gender1) 
}
dplyr(farmData)
```

```{r}
#plotmydata example

plotmydata<-function(x){
  library(magrittr)
  x%>% ggplot2::ggplot()+ggplot2::aes(x=age1, y=educ1)+ggplot2::geom_point()
}
plotmydata(farmData)
```

```{r}
#plots of data

growth <- read.csv("http://www.stat.umn.edu/geyer/3701/data/growth.csv",
                   stringsAsFactors = FALSE)
library(magrittr)
farmData%>% ggplot2::ggplot()+ggplot2::aes(x=age1, y=educ1)+ggplot2::geom_point()
farmData%>% ggplot2::ggplot()+ggplot2::aes(x=age2, y=educ2)+ggplot2::geom_point()
farmData%>% ggplot2::ggplot()+ggplot2::aes(x=age3, y=educ3)+ggplot2::geom_point()
d%>% ggplot2::ggplot()+ggplot2::aes(x=x, y=p)+ggplot2::geom_point()
growth%>% ggplot2::ggplot()+ggplot2::aes(x=HT1, y=HT1)+ggplot2::geom_point()
```